version: "3"
services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db


  node-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      PORT: 5000
      DB: mongodb://mongo_db:27017/SUST_DB
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
